export const JournalPrompts: string[] = [
  "What was the best part of your day today?",
  "What made you smile today?",
  "What's one thing you're looking forward to this week?",
  "What's something you're proud of from today?",
  "What's someone you're thankful for today?",
  "Who made a positive impact on your life recently?",
  "What's a hard lesson you're grateful for?",
  "What obstacles are you facing, and what can you learn from them?",
  "What's something that surprised you today, that you're grateful for?",
  "What's one thing you love about yourself?",
  "What's a personal achievement you're proud of?",
  "What's a relationship in your life you're grateful for?",
  "What's something you love about the current season?",
  "What's something in nature you're grateful for today?",
  "What's a book that had a positive impact on you?",
  "Who's someone from your past that you're grateful for?",
  "What's a guilty pleasure you enjoy?",
  "What's a basic necessity you're grateful for?",
  "What kindness did someone show you today?",
  "Who's someone who always makes you happy?",
  "What simple pleasure did you enjoy today?",
  "What's one happy memory you're grateful for?", 
  "What's something you love about your home?",
  "What's one thing you feel fortunate for in your career?",
  "What's one challenge that you're grateful for?",
  "What's a family tradition you love?",
  "What's one thing you enjoy about your daily routine?",
  "What's a hobby or pastime you're grateful for?",
  "What's something beautiful you saw today?",
  "What's a technology you're grateful for?",
  "What's a talent or skill you're grateful for?",
  "What's one thing you enjoyed about your job today?",
  "What's something you're looking forward to about tomorrow?",
  "What was the highlight of your week?",
  "What about your body are you most grateful for?",
  "What's something you're grateful for in your city?",
  "What are you grateful for in your family?",
  "What's a modern innovation you're grateful for?",
  "What's a comfort you're grateful for?",
  "What's an accomplishment you're proud of?",
  "What was the most enjoyable part of your routine today?",
  "What's something new you learned today?",
  "What's something that made you laugh today?",
  "What was your biggest win today?",
  "What's one thing you were able to complete today?",
  "What's something that felt satisfying to do today?",
  "What's a place you're grateful for?",
  "What's your favorite part of your routine and why?",
  "What are three things that went well today?",
  "What's something that you're glad happened today?",
  "What's something you're grateful for from your childhood?",
  "What's a spontaneous event or surprise that you're grateful for?",
  "What's a challenge you conquered?",
  "What small things that happened today are you grateful for?",
  "What made you truly excited today?",
  "What do you appreciate about your work?",
  "What's something you did well today?",
  "What made you feel peaceful today?",
  "What's something you were given today?",
  "What's the most beautiful thing you saw today?",
  "What's a quote or saying that you're grateful for?",
  "What's a recent purchase you appreciate?",
  "What's a fear or insecurity you're grateful for?",
  "What's a song that makes you feel grateful?",
  "What's a recent change in your life you're grateful for?",
  "What's a meal from today you're grateful for?",
  "What's an adventure or trip that you're grateful for?",
  "What's a tradition you're grateful for?",
  "What's a friend you're grateful for?",
  "What's an attribute of yourself you're proud of?",
  "How did someone extend kindness to you today?",
  "What's a physical quality you're thankful for?",
  "What's an attribute of a specific family member you're grateful for?",
  "What's a book or article that you're grateful for?",
  "What decision are you grateful for making?",
  "What did you enjoy doing in your free time today?",
  "What's something good that happened in the world today?",
  "What's a detail of your daily routine that you're thankful for?",
  "What's a good habit you're grateful for having?",
  "What's a safety or security you're thankful for?",
  "What's a convenience or comfort you're thankful for?",
  "What so-called 'bad' thing happened, and what were the good things that came of it?",
  "What's an 'ugly' thing you're grateful for?",
  "What's a possession that makes your life easier?",
  "What's a modern invention that improves your quality of life?",
  "What's an indulgence you're grateful for?",
  "What's something about your work or career that you're grateful for?",
  "What's something about your health or body you're thankful for?",
  "What's something about your home you're thankful for?",
  "What's a skill you learned this year you're thankful for?",
  "What's something about your family you're grateful for?",
  "What's something from this year you're grateful for?",
  "What's a mistake or failure from this year that you appreciate, and what did it teach you?",
  "What's something about your community you're thankful for?",
  "What moment of beauty did you observe today?",
  "What's a tradition that you cherish?",
  "What's a relationship that improved this year?",
  "What's a new relationship that you cherish?",
  "What did you accomplish this year that you're proud of?",
  "What moment are you grateful you lived to experience?",
  "What skill are you most glad to possess?",
  "What part of your life feels abundant?",
  "What made you feel connected to others this year?",
  "What made you feel loved this year?",
  "What made you proud of yourself this year?",
  "What are you looking forward to in the upcoming year?"
];

export const PERSONAL_ACHIEVEMENTS = {
  title: 'Personal Achievements',
  prompts: [
    "List three personal achievements you are most proud of.",
    "What's a personal goal you recently achieved? How did it make you feel?",
    "Describe a personal achievement that was particularly challenging. How did you overcome it?",
    "What personal achievement brought you the most satisfaction? Why?",
    "Think of a personal achievement that surprised you. Why was it surprising?",
    "What personal achievement have you gained through hard work?",
    "What small personal achievement have you recently celebrated?",
    "Reflect on a personal achievement that improved your self-esteem.",
    "What personal achievement are you working towards right now?",
    "List five personal achievements that have shaped your life.",
    "Do you have a personal achievement others recognize you for? Describe it.",
    "Describe an achievement of your own that taught you the most.",
    "What's a personal achievement you would like to repeat?",
    "Describe a personal achievement that required resilience.",
    "Recall a personal achievement that required patience. How did it feel to succeed?",
    "Describe a personal achievement you didn't expect to accomplish.",
    "Write about a personal achievement that improved your career.",
    "Describe a personal achievement you accomplished with the support of others.",
    "Mention a personal achievement that has made your family proud.",
    "Write about a recent personal achievement. What were the steps you took to reach it?",
    "What's the most artistic achievement you have accomplished?",
    "List three personal achievements that improved your overall happiness.",
    "Reflect on a personal achievement that made you realize a strength you didn't know you had.",
    "Write about a personal achievement in high school, what impact did it have on you?",
    "What's one personal achievement you're still working toward?",
    "What's a personal achievement that has greatly influenced your life?",
    "Describe a personal achievement that made you proud.",
    "Write about an achievement that helped you grow personally.",
    "Reflect on five personal achievements over the past year.",
    "What's an achievement that allowed you to help other people?",
    "What personal achievement positively affected your mental health?",
    "Write about a personal achievement that stretched your limits.",
    "Describe a personal achievement that showcased your skills.",
    "Reflect on a personal achievement that helped improve a relationship in your life.",
    "What personal achievement are you most grateful for and why?",
    "Describe an achievement that taught you a new skill.",
    "What's the smallest personal achievement that gave you the biggest joy?",
    "Write about an achievement from your childhood that you are still proud of.",
    "Reflect on a personal achievement that helped you become more confident.",
    "What personal achievement made you feel like you could achieve anything?",
    "What personal achievement helped change your mindset?",
    "Write about an achievement that introduced you to new people or cultures.",
    "What personal goal are you close to achieving?",
    "Reflect on a personal achievement that came from a failure or setback.",
    "What personal achievement from the past month are you most proud of?",
    "What's the toughest personal achievement you’ve had to obtain?",
    "Describe a personal achievement where you had to overcome fears.",
    "Recount a personal achievement that seemed impossible at first.",
    "Write about a personal achievement that increased your understanding of others.",
    "Reflect on a personal achievement that made you a better leader.",
    "Describe a personal achievement that changed your perspective on life."
  ],
};

export const RELATIONSHIPS = {
  title: 'Relationships',
  prompts: [
    "What relationship are you most grateful for today and why?",
    "List three ways your partner has made you feel loved recently",
    "Who taught you an important life lesson recently?",
    "Who is a person that made you smile today and why?",
    "Write about a surprise act of kindness you received from a loved one",
    "Who brings you joy and how do they bring it?",
    "List three things you love about your best friend",
    "What is the best relationship advice you've ever received?",
    "Write about a time your spouse stood by your side",
    "Who has helped you grow and how?",
    "Write about a friend who has been there in difficult times",
    "Reflect on the most comforting words a loved one has shared with you",
    "Write about an act of forgiveness you've experienced in a relationship",
    "What have you learned from your parents about love & friendships?",
    "Who from your past are you grateful for, what has that relationship taught you?",
    "What is something positive you've noticed about your co-worker?",
    "What was the last compliment you received from a loved one?",
    "Write about an old friend who you’re grateful for",
    "Name a trait of someone you enjoy spending time with",
    "Who do you feel close to even if you're not physically close?",
    "List some ways your friends have helped you this year",
    "What is a happy memory you shared with a loved one?",
    "What is something a relation did for you that they didn’t have to do?",
    "Reflect on the supportive relationships you have in your life",
    "Who do you trust and why are you grateful for them?",
    "Write about an instance when your pet made your day better",
    "What qualities do you admire in your close ones?",
    "How are your loved ones helping you become a better person?",
    "Who do you enjoy being around and why?",
    "Who brought positivity into your life today, and how?",
    "What are you looking forward to with a particular relationship?",
    "Who helped you achieve a goal and how?",
    "Reflect on a moment when a teacher impacted your life positively",
    "What are some acts of love you've witnessed recently?",
    "What is something kind your neighbor did recently?",
    "Name someone who makes you feel understood",
    "What about your friends do you appreciate?",
    "Who do you share your secrets with and why do you trust them?",
    "What is a silly, yet endearing, habit of a loved one?",
    "Who is your rock during hard times?",
    "How did having a conversation with a loved one made your day better?",
    "What is one relationship you feel has shaped your life?",
    "Who do you feel most comfortable around, and why?",
    "Reflect on the strengths of your long-term relationships",
    "How has your partner shown support recently?",
    "What is a memory of laughter shared with a loved one?",
    "Who makes you feel confident and how?",
    "How has someone’s kindness toward you made a difference recently?",
    "Who brought you comfort recently?",
    "Write about a relationship you’ve seen grow stronger over time",
    "What was something special someone did for you recently?",
    "Write about a memory you made with a loved one that still makes you smile"
  ],
};

export const PHYSICAL_HEALTH = {
  title: 'Physical Health',
  prompts: [
    "What's one physical activity that I truly enjoy?",
    "What's my favourite healthy dish?",
    "What part of my physical health am I most thankful for today?",
    "How did a physically active hobby or interest improve my life?",
    "What's a new physical ability I learned this year that I'm grateful for?",
    "What physical achievement am I most proud of?",
    "What is one aspect of my physical health I've seen improve over the past year?",
    "What healthy habits am I grateful I've incorporated into my lifestyle?",
    "What're some physical strengths I am thankful for?",
    "What are three ways my body surprised me in a good way?",
    "What are some benefits of good health that I sometimes take for granted?",
    "How has my relationship with my body improved?",
    "What specific health challenges have I overcome that I'm thankful for?",
    "What's one self-care activity that benefits my physical health?",
    "What is one way my body helps me experience joy every day?",
    "What is one active activity I do regularly that I truly enjoy?",
    "What food makes me feel healthy and happy?",
    "How does a good night's sleep improve my day?",
    "What is one goal related to physical health that I accomplished?",
    "What is one physical feature that I love about myself?",
    "What steps have I taken towards a healthier lifestyle that I'm proud of?",
    "What is something about my body that I love and respect?",
    "How has my body supported me in a challenging physical activity?",
    "What part of my morning routine invigorates me?",
    "What's a new healthy recipe that I tried and loved recently?",
    "What exercise or workout am I thankful for?",
    "How has maintaining physical health positively impacted my life?",
    "What physical improvement am I thankful for achieving?",
    "What are five physical traits that I love about myself?",
    "What are three things that my body allows me to do that I enjoy?",
    "How has my body been resilient in times of illness or stress?",
    "What aspects of my health do I feel grateful for when I think about others who lack it?",
    "What is one body part that I am especially grateful for today?",
    "Why am I grateful for my ability to exercise?",
    "What personal records have I broken in the gym that I'm proud of?",
    "What is one physical milestone that I'm grateful for reaching?",
    "What self-care practices contribute to my physical well-being?",
    "How is my body stronger now than it was one year ago?",
    "How has a physical challenge helped me grow?",
    "What are five physical activities that bring me pleasure?",
    "How did a significant illness or injury deepen my appreciation for health?",
    "What physical senses am I most thankful for?",
    "What seasonal fruits or vegetables am I currently enjoying?",
    "How do I appreciate my body even when it's weaker or less capable?",
    "What aspect of my appearance do I feel most confident about?",
    "How has a healthy diet improved my life?",
    "What act of kindness did my body perform for someone else?",
    "How has exercise helped me handle stress?",
    "How does it feel to stretch out when I wake up in the morning?",
    "What body movement brings me joy or relief?",
    "What did I physically survive that I'm thankful for today?"
  ],
};

export const EMOTIONAL_GROWTH = {
  title: 'Emotional Growth',
  prompts: [
    "What is one experience that has sparked the most personal growth in you?",
    "How has a particular hardship lead you to emotional growth?",
    "What kind of emotional growth have you experienced this past year?",
    "What are five positive changes in your emotional state you are grateful for?",
    "Who has helped you grow emotionally and why are you thankful for them?",
    "What past emotional challenges are you now grateful for, due to the growth they caused?",
    "Name an emotionally challenging situation that helped you understand compassion better.",
    "How have you grown in terms of patience and gratitude over the last year?",
    "What negative emotional habit are you proud of overcoming?",
    "How have your relationships influenced your emotional growth?",
    "What steps have you taken recently to progress towards your emotional growth?",
    "What personal strengths have you developed through facing emotional challenges?",
    "What conversation led to a noticeable emotional growth in you?",
    "How were you able to turn a negative emotion into a positive learning experience?",
    "Who or what inspired your most recent emotional growth?",
    "What is one moment of emotional growth that you didn't realize until later?",
    "How do you feel your emotional growth has impacted your life positively?",
    "Name a book or movie that significantly affected your emotional growth.",
    "How has practicing gratitude contributed to your emotional growth?",
    "What are three emotional achievements you are proud of this year?",
    "What emotional risks have you taken that led to personal growth?",
    "How did facing a rejection or failure contribute to your emotional growth?",
    "How has an emotional setback helped you grow stronger or develop emotional resilience?",
    "What piece of advice triggered a significant emotional growth in you?",
    "Who has challenged you to grow emotionally and why are you grateful for them?",
    "How has travel or new experiences influenced your emotional growth?",
    "What emotional barriers have you overcome and how did it contribute to your growth?",
    "How has your spiritual belief system impacted your emotional growth?",
    "Write about a life changing decision that lead to your emotional growth.",
    "What is a moment in your life where you felt emotionally matured and extremely grateful?",
    "How has self-care contributed to your emotional growth?",
    "What habits have you developed for your emotional health?",
    "Talk about a practice you have taken on to grow emotionally.",
    "How has your understanding of others' emotions grown over time?",
    "What gratitude habit has led to your emotional growth?",
    "What are some emotional challenges you were able to overcome and feel thankful for?",
    "How has accomplishing a personal goal contributed to your emotional growth?",
    "What experience broadened your perspective and helped you grow emotionally?",
    "What is a childhood event you're grateful for because of the emotional growth it brought you?",
    "How do your emotional growth goals look like for the next year?",
    "Write about a person you actually thanked for helping you grow emotionally.",
    "What are some unhealthy emotional patterns you are thankful for letting go?",
    "What skills have you learnt that have aided in your emotional growth?",
    "How has your job or career contributed to your emotional growth?",
    "How has a particular hobby or interest led to your emotional growth?",
    "How has continuous learning or education impacted your emotional growth?",
    "Discuss a situation where you had to be emotionally strong and now you are grateful for it.",
    "Describe an experience which ignited emotional maturity within you.",
    "What are the top five emotions you have had to improve and grow on?",
    "What was a great piece of advice you received and still cherish due to the emotional growth it resulted in?"
  ]
};

export const PERSONAL_LIFE = {
  title: 'Personal Life',
  prompts: [
    "What is something that made you smile today in your personal life?",
    "What personal achievement are you most proud of?",
    "Who is someone in your personal life you feel grateful for?",
    "What is a challenge in your personal life you've overcome that you're proud of?",
    "What about your health and wellbeing are you thankful for?",
    "Who made a positive impact in your personal life recently?",
    "What unexpected joy did you encounter today?",
    "What is a lesson you've learned recently in your personal life?",
    "What is something in your personal life that you used to take for granted but now appreciate?",
    "What was the best moment of your day today?",
    "Who in your personal life enriches your life the most?",
    "What talents or skills are you thankful for?",
    "What is your favourite personal tradition?",
    "How have your past failures in personal life led to growth opportunities you’re thankful for now?",
    "What moment from your past are you grateful for?",
    "What act of kindness did you witness or that was done for you recently?",
    "What is your favourite daily personal routine?",
    "What relationship in your personal life are you thankful for?",
    "What hobby or pastime do you feel lucky to be able to enjoy?",
    "What was a recent piece of good news you received?",
    "What part of your home do you feel most comfy and happy in?",
    "What's a book, movie or song that influenced your personal life positively?",
    "What's a personal goal that you've recently achieved?",
    "Who was kind to you in your personal life this week?",
    "What recent personal accomplishment are you proud of?",
    "What family tradition makes you feel grateful?",
    "What was the best part of your morning today?",
    "What is something about your personal life that excites you?",
    "What is something that made you laugh in your personal life this week?",
    "What is a flaw you're glad you have?",
    "What part of your day are you most grateful for?",
    "How has a hardship in your personal life made you a better person?",
    "What change recently improved your personal life?",
    "What is something that you love about your current lifestyle?",
    "Who in your personal life do you admire and why?",
    "What's your favourite personal item and why?",
    "What peaceful activities bring a sense of calm and gratitude over you?",
    "What's a recent interaction or conversation that left a positive impact on you?",
    "What childhood memory makes you feel gratitude?",
    "What's something you're looking forward to in your personal life?",
    "Who or what inspired you today in your personal life?",
    "What's something that helped you de-stress recently?",
    "How is a loved one showing you love lately?",
    "What aspect of your daily lifestyle are you thankful for?",
    "What personal freedom are you grateful for?",
    "What beauty have you noticed in your surroundings lately?",
    "How did a friend in your life recently display a quality you admire?",
    "What is something in nature you’re grateful for?",
    "What's one thing about yourself that makes you feel proud?",
    "What simple pleasure from your personal life made a big impact on you?"
  ],
};

export const NATURE_AND_ENVIRONMENT = {
  title: 'Nature and Environment',
  prompts: [
    "What are some natural wonders you're thankful for?",
    "What’s something in nature you saw today that you’re grateful for?",
    "What aspects about the weather today are you thankful for?",
    "What is a way the environment protects you that you are thankful for?",
    "What is a way nature soothes you that you are thankful for?",
    "What season are you most grateful for and why?",
    "Describe in detail a moment in nature that took your breath away.",
    "What body of water (river, lake, ocean) are you most grateful for and why?",
    "What kind of weather makes you feel most alive and grateful?",
    "What are some sounds in nature that you are grateful for?",
    "What is your favorite plant and why are you thankful for it?",
    "What is one way nature helped you maintain your sanity during a tough period?",
    "What is the most beautiful place you have been to and why are you thankful for it?",
    "What hiking, camping, or backpacking trip are you most grateful for?",
    "Describe a memory you have of watching the sunset or sunrise.",
    "What is a favorite memory you have of time spent in nature?",
    "Write about how the changing seasons make you feel.",
    "How has being outdoors improved your mental health?",
    "What's one piece of knowledge you've learned from nature?",
    "What is your most cherished memory in a natural location?",
    "What natural location are you most looking forward to visiting?",
    "What are some natural processes or natural phenomena that you are thankful for?",
    "What is your favorite memory involving the night sky?",
    "What bird or animal sighting has brought you joy?",
    "How has a body of water brought peace to your life?",
    "What do you appreciate most about your favorite season?",
    "What is your favorite type of weather, and why are you thankful for it?",
    "How does the ocean make you feel thankful?",
    "What elements of nature inspire you?",
    "Which tree are you most thankful for and why?",
    "What natural discovery have you made that you are most grateful for?",
    "How has nature taught you patience?",
    "Who would you thank for teaching you to appreciate nature?",
    "What's the best camping trip you've ever taken?",
    "What discoveries in nature have surprised you the most?",
    "What part of nature makes you feel calmest?",
    "Write about the last time nature made you laugh.",
    "What part of nature gives you the most hope?",
    "Describe a time where the beauty of nature left you speechless.",
    "How does being in nature make you feel grounded?",
    "How has nature played a role in your spiritual life?",
    "What do you love most about your local environment?",
    "Describe a time when nature took your breath away.",
    "What are some ways the natural world has healed you?",
    "What natural textures do you really love?",
    "What's the most spectacular natural sight you've ever seen?",
    "Who in your life has helped deepen your connection to nature?",
    "What's your favorite nature-related memory from your childhood?",
    "What qualities do you appreciate the most about animals in nature?",
    "How has nature brought you closer to your loved ones?"
  ]
};

export const SPIRITUAL_GROWTH = {
  title: 'Spiritual Growth',
  prompts: [
    "What spiritual practice benefited you today?",
    "What spiritual lesson did you learn today?",
    "What aspect of your spirituality are you a most grateful for?",
    "How have you grown spiritually over the last month?",
    "What was the hardest spiritual lesson you learned that you're thankful for?",
    "What part of your spiritual journey are you most proud of?",
    "How does your spirituality help you in daily life?",
    "What personal traits have you developed because of your spirituality?",
    "How had your spirituality improved the quality of your life?",
    "Reflect on someone who has positively influenced your spiritual growth.",
    "What spiritual book or teachings are you most grateful for?",
    "What are some actions in your daily routine that bring you spiritual fulfillment?",
    "What spiritual goal did you reach recently?",
    "Who has inspired you to grow spiritually, and how?",
    "When was the last time you felt spiritually connected with others?",
    "How does your current spiritual progress makes you feel?",
    "What spiritual milestone have you achieved that you're thankful for?",
    "How does your spirituality impact your relations with others?",
    "Which spiritual event or ceremony has left a deep impact on you?",
    "Why are you grateful for your spiritual beliefs?",
    "What changes have you noticed in yourself thanks to spiritual growth?",
    "What challenging situation drove your spiritual growth?",
    "How has your prayer or meditation practice improved over time?",
    "How does being spiritual help you during hard times?",
    "What spiritual values are you most thankful for?",
    "What does spiritual growth mean to you?",
    "How important is spirituality in your life?",
    "What spiritual experience made the most profound impact on you?",
    "How has spirituality helped you become more authentic?",
    "What spiritual symbol or item are you most grateful for?",
    "What moment of serendipity strengthened your faith or spirituality?",
    "How has your spiritual growth affected your relationship with nature?",
    "What spiritual music or songs elicit strong feelings of gratitude in you?",
    "What moments of solitude have helped you grow spiritually?",
    "What spiritual traditions are you most thankful for?",
    "How does your spirituality help you stay grounded?",
    "Write about a time you felt in complete harmony with the universe.",
    "How do you express gratitude toward your spiritual guides?",
    "Reflect on a personal flaw you overcame thanks to spiritual growth.",
    "What's one thing you did today that aligned with your spiritual values?",
    "How has your spirituality helped you in dealing with fear?",
    "Reflect on a moment of forgiveness that lead to spiritual growth.",
    "What spiritual rituals are you most thankful for?",
    "What questions does your spiritual growth trigger in you?",
    "Write about a moment of clarity or enlightenment you've experienced.",
    "How has your spiritual journey changed you as a person?",
    "How has your spiritual growth supported your mental health?",
    "What spiritual affirmations help you in your daily life?",
    "Reflect on spiritual growth in connection with self-love.",
    "What spiritual teachings are you most thankful for and why?"
  ]
};

export const TRAVEL_AND_ADVENTURE = {
  title: 'Travel and Adventure',
  prompts: [
    "List out 5 unexpected adventures you've encountered while traveling.",
    "What location that you've visited are you most thankful for?",
    "Write about a meaningful interaction you had with a local during your travels.",
    "Detail a travel experience that changed your outlook on life.",
    "What is the most stunning sight you've seen on your adventures?",
    "How has traveling enriched your life?",
    "Who in your travels are you most grateful for meeting and why?",
    "Recall a frightening experience you overcame during one of your journeys.",
    "Write about your favorite travel memory.",
    "What is one place you visited that felt like home and why?",
    "How did you feel when you visited a new country for the first time?",
    "List five things you learnt during your last trip.",
    "Explain how traveling has shaped your view of the world.",
    "What travel-related accomplishments are you most proud of?",
    "Describe a memorable meal you had while traveling.",
    "Who is someone that made your traveling experience special? What did they do?",
    "Why are you grateful for the opportunity to travel?",
    "What about nature have you learned or appreciated more through traveling?",
    "Has traveling made you more adventurous? Explain how.",
    "Which travel experience has made you truly appreciate life and why?",
    "What is a unique cultural experience you had while traveling that you're grateful for?",
    "Recall a moment of solitude you experienced while traveling.",
    "What is a special souvenir you've gotten from your travels? Why is it meaningful?",
    "Write about a refreshing outdoor activity you did on your travels.",
    "What unplanned adventure ended up being a memorable experience?",
    "Describe a travel experience that brought you a peace of mind.",
    "Detail a time when traveling challenged you and how you grew from it.",
    "In which ways has traveling made you more grateful for what you have?",
    "How has traveling helped you step outside of your comfort zone?",
    "Have you ever felt inspired by a city or country during your travels? Describe that feeling.",
    "What historical sight you've visited has left the most impact on you?",
    "What was the most difficult part of your travels and how did you overcome it?",
    "Describe any kind act someone did for you while on your travels.",
    "How did you feel when you achieved a travel goal you set for yourself?",
    "Have your travels ever brought you any new passions or hobbies?",
    "Can you recall a moment during your travels where you felt supremely happy?",
    "Have you ever made lifelong friends on your travels? Describe that relationship.",
    "Write about your favorite calming spot you've found during your travels.",
    "Describe an adventurous activity you tried for the first time while traveling.",
    "How do you feel when you return home after a long trip, and why?",
    "Have you learned any new skills during your adventures? What are they?",
    "What was your favorite family vacation and why?",
    "Write about a moment when you got lost during your travels and what you gained from the experience.",
    "How have your travels taught you to be more present in the moment?",
    "What new event or festival you've attended in a different country are you thankful for?",
    "Do you prefer traveling alone or with others, and why?",
    "Detail the most beautiful sunrise or sunset you've witnessed on your travels.",
    "How has traveling impacted your perspective on your own culture and lifestyle?",
    "Discuss a memorable journey you took by car, train, boat, or plane.",
    "What is a priceless moment from your travels?"
  ],
};

export const ARTISTIC_EXPRESSION = {
  title: 'Artistic Expression',
  prompts: [
    "What are five pieces of art you are grateful for?",
    "What piece of artistic expression did you see recently that inspired you?",
    "How have artistic influences played a role in your life?",
    "Think of your favorite film. Why are you grateful for it?",
    "Consider a documentary you are grateful for. Why does it resonate with you?",
    "Describe a song that you are grateful for, and why it means so much to you.",
    "What piece of literature are you most grateful for and why?",
    "Who is an artist you are grateful for their creative influence in your life?",
    "What ways are you grateful for artistic expression as a form of communication?",
    "What use of color in an artwork are you most thankful for and why?",
    "Why are you grateful for your favorite art form?",
    "How does music influence your life in ways that you are grateful for?",
    "How has a piece of theater or performance art impacted you?",
    "What art museum or exhibit are you most thankful to have experienced?",
    "What piece of art you created are you most thankful for?",
    "What moments of beauty in nature have mirrored a piece of art you are grateful for?",
    "How have books enriched your life in ways you are thankful for?",
    "Why are you grateful for artwork within your community?",
    "Reflect on a photograph that touched your heart. Why are you grateful for it?",
    "How have paintings or sculptures made you see the world differently and sparked gratitude?",
    "What artistic skill are you most grateful to possess?",
    "Describe a particular dance performance that you are thankful for.",
    "Tell about an artwork that helped you through a difficult time.",
    "Write about a memorable concert/event you're grateful for having attended.",
    "How does the imagination and creativity of others inspire feelings of gratitude in you?",
    "What piece of street art are you grateful for, and why does it hold meaning for you?",
    "Describe a fashion style or designer you're thankful for.",
    "What piece of poetry or prose are you grateful for, and why?",
    "How does the art in your home bring a sense of gratitude?",
    "Think of an iconic architecture that you’re grateful for. Why does it inspire you?",
    "Why do you feel gratitude towards storytelling and script writing?",
    "What cultural art form are you thankful for, and why?",
    "How does the artistic expression of others encourage your sense of gratitude about life?",
    "Which piece of abstract art has caught your eye and sparked gratitude? Why?",
    "What sculpture have you seen that you're grateful for, and why?",
    "Describe an art form from your childhood you are grateful for.",
    "List five artworks that positively impacted your life.",
    "What art supplies or tools are you most thankful for?",
    "Why are you grateful for the diversity in artistic expressions around the world?",
    "How has digital art opened new perspectives for you to be grateful for?",
    "Recall an artistic experience that fostered a sense of community in your life.",
    "What role does art play in your daily self-expression that makes you grateful?",
    "Write about a quote from an artist you're thankful for.",
    "Reflect on how art helps you understand different cultures and why you're grateful for this.",
    "Express your gratitude for a fictional character that has deeply influenced you.",
    "What is one piece of art you are grateful to have in your personal collection, and why?",
    "Why do you feel gratitude towards impressionist art?",
    "What TV show has had a profound impact on your life and why you're thankful for it?",
    "How has writing been a medium of artistic expression that you're grateful for?",
    "What graffiti artwork are you thankful for and how does it inspire you?"
  ]
};

export const EDUCATION_AND_LEARNING = {
  title: 'Education and Learning',
  prompts: [
    "Highlight a teacher or mentor who made a significant impact on your education journey.",
    "Write about a subject or topic that you are grateful to have learned.",
    "Reflect on a valuable lesson you learned from a mistake or failure in your education.",
    "Express gratitude for the resources and tools that have helped you in your learning process.",
    "Write about a book or article that had a major influence on your perspective or knowledge.",
    "Reflect on a project or assignment that challenged you and helped you grow academically.",
    "Express gratitude for the opportunities you have had to participate in extracurricular activities or clubs.",
    "Write about a classmate or colleague who has been supportive and helpful in your education.",
    "Reflect on a study technique or strategy that has significantly improved your learning experience.",
    "Express gratitude for the internet and other technological advancements that have enhanced education.",
    "Write about a new skill or concept you recently learned and are grateful for.",
    "Reflect on a field trip or educational excursion that provided valuable learning experiences.",
    "Express gratitude for the accessibility and inclusivity initiatives in education.",
    "Write about a specific moment when you felt inspired or motivated in your educational journey.",
    "Reflect on a challenging concept or subject that you eventually mastered.",
    "Express gratitude for the opportunity to receive a formal education.",
    "Write about a time when a teacher believed in you and encouraged you to reach your potential.",
    "Reflect on the impact of a particular educational program or initiative in your life.",
    "Express gratitude for the opportunity to learn different languages.",
    "Write about a study group or collaborative learning experience that helped you succeed academically.",
    "Reflect on a time when you overcame a learning obstacle or setback.",
    "Express gratitude for scholarships or financial aid that have made education affordable for you.",
    "Write about a course or program that broadened your knowledge beyond your expectations.",
    "Reflect on a graduation or achievement that you are proud of.",
    "Express gratitude for the libraries and educational institutions that have supported your learning.",
    "Write about a moment when you realized the value of lifelong learning.",
    "Reflect on a volunteer or mentoring experience that positively impacted your educational journey.",
    "Express gratitude for the diverse range of educators who have shared their expertise with you.",
    "Write about a particular learning environment that fostered your growth and development.",
    "Reflect on a time when you utilized your education to help others or make a positive difference.",
    "Express gratitude for the freedom to explore different fields of study and pursue your passions.",
    "Write about a class or lecture that challenged your perspective and made you think critically.",
    "Reflect on a time when education helped you overcome a personal or professional obstacle.",
    "Express gratitude for the friends or connections you made through your educational journey.",
    "Write about a motivational quote or saying that has guided your approach to learning.",
    "Reflect on a teacher or professor who went above and beyond to support your educational goals.",
    "Express gratitude for the ability to access educational resources and information anytime, anywhere.",
    "Write about a moment when you realized the impact of education on societal progress.",
    "Reflect on a lesson outside of the traditional curriculum that has shaped your worldview.",
    "Express gratitude for the opportunity to pursue higher education and expand your horizons.",
    "Write about a collaborative project or group assignment that helped you develop teamwork skills.",
    "Reflect on a time when education empowered you to confront and overcome a personal challenge.",
    "Express gratitude for the educational institutions and organizations that have contributed to your growth.",
    "Write about a skill or knowledge you acquired that has been beneficial in your career.",
    "Reflect on a time when education provided a platform for you to express your creativity.",
    "Express gratitude for the mentors or advisors who have guided you throughout your educational journey.",
    "Write about a teacher or professor who made learning enjoyable and engaging for you.",
    "Reflect on a time when education helped you develop problem-solving skills in real-life situations.",
    "Express gratitude for the knowledge and understanding gained through education.",
    "Write about a grateful moment when you witnessed someone else benefiting from education.",
    "Reflect on a time when education helped you overcome a stereotype or prejudice.",
    "Express gratitude for the support systems that have encouraged and motivated you in your education.",
    "Write about a specific educational philosophy or approach that resonates with you.",
    "Reflect on a time when education opened doors of opportunity for you.",
    "Express gratitude for the educators who have taught you valuable life lessons beyond the subject matter."
  ]
};

export const FINANCES_AND_AMENITIES = {
  title: 'Finances and Amenities',
  prompts: [
    "Reflect on a time when you were grateful for receiving unexpected financial help.",
    "Write about a financial goal you achieved and how it positively impacted your life.",
    "Express gratitude for the amenities you have access to on a daily basis.",
    "Think about a luxury item you own and appreciate the hard work it took to acquire it.",
    "Write about a time when you were grateful for the convenience of online banking.",
    "Express thanks for the opportunities you have had to travel and experience different cultures.",
    "Reflect on a time when you were grateful for finding a great deal on a purchase.",
    "Write about a time when you were grateful for a raise or promotion at work.",
    "Express gratitude for the amenities available in your local community.",
    "Think about a time when you were grateful for having the financial means to help a loved one in need.",
    "Write about a time when you were grateful for receiving a scholarship or financial aid.",
    "Express thanks for the ability to enjoy a hot shower or bath every day.",
    "Reflect on a time when you were grateful for receiving an unexpected discount or coupon.",
    "Write about a time when you were grateful for being able to afford a meal at your favorite restaurant.",
    "Express gratitude for having a reliable vehicle to commute or travel with.",
    "Think about a time when you were grateful for having reliable and affordable public transportation options.",
    "Write about a time when you were grateful for the financial resources to pursue a hobby or passion.",
    "Express thanks for the amenities available in your workplace or office.",
    "Reflect on a time when you were grateful for receiving financial advice that improved your situation.",
    "Write about a time when you were grateful for receiving a gift card or voucher for a desired purchase.",
    "Express gratitude for the amenities available in your neighborhood or apartment complex.",
    "Think about a time when you were grateful for having the means to donate to a charitable cause.",
    "Write about a time when you were grateful for a sale or discount that allowed you to save money.",
    "Express thanks for the opportunity to attend concerts, shows, or other cultural events.",
    "Reflect on a time when you were grateful for the convenience of online shopping.",
    "Write about a time when you were grateful for having the financial ability to pursue higher education.",
    "Express gratitude for the amenities available at your gym or fitness center.",
    "Think about a time when you were grateful for having access to affordable healthcare.",
    "Write about a time when you were grateful for being able to afford a family vacation.",
    "Express thanks for the financial resources that allow you to support local businesses.",
    "Reflect on a time when you were grateful for receiving an unexpected bonus or monetary gift.",
    "Write about a time when you were grateful for having access to high-speed internet.",
    "Express gratitude for the amenities available at your local park or outdoor recreational area.",
    "Think about a time when you were grateful for receiving a refund or reimbursement.",
    "Write about a time when you were grateful for having enough money for comfortable and warm clothing.",
    "Express thanks for the opportunity to enjoy a good book or movie.",
    "Reflect on a time when you were grateful for the financial ability to adopt a pet.",
    "Write about a time when you were grateful for having access to reliable and affordable childcare.",
    "Express gratitude for the amenities available at your favorite vacation destination.",
    "Think about a time when you were grateful for having the means to invest and plan for your future.",
    "Write about a time when you were grateful for being able to afford professional development opportunities.",
    "Express thanks for the financial resources that allow you to attend conferences or workshops.",
    "Reflect on a time when you were grateful for the convenience of online bill payment.",
    "Write about a time when you were grateful for having access to free or affordable educational resources.",
    "Express gratitude for the amenities available at your local library.",
    "Think about a time when you were grateful for receiving a grant or funding for a project.",
    "Write about a time when you were grateful for having the financial means to support a cause you believe in.",
    "Express thanks for the opportunity to enjoy a delicious meal with friends or loved ones."
  ],
};


export const ALL_PROMPTS = {
  PERSONAL_ACHIEVEMENTS,
  RELATIONSHIPS,
  PHYSICAL_HEALTH,
  EMOTIONAL_GROWTH,
  PERSONAL_LIFE,
  NATURE_AND_ENVIRONMENT,
  SPIRITUAL_GROWTH,
  TRAVEL_AND_ADVENTURE,
  ARTISTIC_EXPRESSION,
  EDUCATION_AND_LEARNING,
  FINANCES_AND_AMENITIES,
};